### ISSUE TITLE
Error - Adding Style to XAML

### ISSUE THREAD

**Issue by rufreakde** [Videogamers0/MGUI#11]
Whenever one tries to add any style it fails on XML parsing. Not sure how to get styles to work especially something like hover would be nice.
![image](https://github.com/Videogamers0/MGUI/assets/28104368/159e9572-f92c-4878-8687-dc58d071fa2d)

```xml
<Window xmlns="clr-namespace:MGUI.Core.UI.XAML;assembly=MGUI.Core"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:local="clr-namespace:MGUI.Samples.Dialogs.FF7;assembly=MGUI.Samples"
        WindowStyle="None"
        Left="400" Top="400" Width="480" Height="620"
        BorderBrush="Crimson" BorderThickness="0" Background="White" TextForeground="Black" 
        Padding="20" TitleText="Main Menu" IsUserResizable="False" MinHeight="0" SizeToContent="WidthAndHeight">

    <Button.Styles>
        <Style TargetType="Button">
            <Setter Property="FontSize" Value="14" />
            <Setter Property="Foreground" Value="rgb(236,236,236)" />
            <Setter Property="IsShadowed" Value="True" />
            <Setter Property="ShadowColor" Value="Black" />
            <Setter Property="ShadowOffset" Value="1,2" />
        </Style>
    </Button.Styles>

    <StackPanel Orientation="Vertical" Background="Red" Height="50" Spacing="20">
        <Button Name="Play" Content="Play" HorizontalContentAlignment="Center" VerticalContentAlignment="Center"/>
        <Button Name="Settings" Content="Settings" HorizontalContentAlignment="Center" VerticalContentAlignment="Center" />
        <Button Name="UnitEditor" Content="Unit Editor" HorizontalContentAlignment="Center" VerticalContentAlignment="Center" />
        <Button Name="OfficerEditor" Content="Officer Editor" HorizontalContentAlignment="Center" VerticalContentAlignment="Center" />
        <Button Name="TerrainEditor" Content="Terrain Editor" HorizontalContentAlignment="Center" VerticalContentAlignment="Center" />
    </StackPanel>
</Window>
```

Removing Button.Styles section works.

I tried to have something simple with triggers:
```xml
            <Button.Style>
                <Style TargetType="Button">
                    <Setter Property="Offset" Value="0, 0, 0, 0"/>
                    <Style.Triggers>
                        <Trigger Property="IsMouseOver" Value="True">
                            <Setter Property="Offset" Value="15, 3, 6, 25"/>
                        </Trigger>
                        <Trigger Property="IsPressed" Value="True">
                            <Setter Property="Offset" Value="5, 0, 12, 10"/>
                        </Trigger>
                    </Style.Triggers>
                </Style>
            </Button.Style>
```

Any ideas?

**Comment by Videogamers0** [comment]
The 1st XAML you provided works fine for me if you change `<Button.Styles>` to `<Window.Styles>` since the element is a Window.

The 2nd XAML does not work for a couple reasons:
1. There is no `Offset` property on `MGElement`s. Not all WPF properties are implemented in MGUI.
2. The `Style` implementation is very basic - it only supports simple setters. It doesn't have support for event setters, triggers, or data triggers. You'd have to implement the desired setters logic yourself in your code, such as by subscribing to `MGElement.OnBeginUpdate`, and setting the appropriate property based on `MGElement.VisualState.Secondary` if you wanted to modify a value when an element is pressed/hovered.

**Comment by rufreakde** [comment]
@Videogamers0 thanks for your quick response!
> You'd have to implement the desired setters logic yourself in your code, such as by subscribing to MGElement.OnBeginUpdate, and setting the appropriate property based on MGElement.VisualState.Secondary

I think I will go for that then just going to build some class that has that logic in place and read your docs regarding the `MGElement.OnBeginUpdate`!

Okay so I am able to set styles but I am not able to use triggers for that custom code in c# is required! Got it thanks!

**Comment by rufreakde** [comment]
> The 1st XAML you provided works fine for me if you change `<Button.Styles>` to `<Window.Styles>` since the element is a Window.
> 
> The 2nd XAML does not work for a couple reasons:
> 
> 1. The `Offset` property is a generic property that's only used by elements that are children of certain parent types. I think `Offset` was for children of `OverlayPanel`s. In WPF this would be attached properties, such as `DockPanel.Dock=Top`. But I didn't know how to implement attached properties in XAML parsing, so instead every element has the attached properties even though they might not apply to the element. For example, an element placed within a `StackPanel` still has a `Dock` property even though it's not a child of a `DockPanel`.
> 2. The `Style` implementation is very basic - it only supports simple setters. It doesn't have support for event setters, triggers, or data triggers. You'd have to implement the desired setters logic yourself in your code, such as by subscribing to `MGElement.OnBeginUpdate`, and setting the appropriate property based on `MGElement.VisualState.Secondary` if you wanted to modify a value when an element is pressed/hovered.

ps I tried to use Button.Styles inside of buttons but it did not work... but you are right Window.Styles in the window worked for me as well!

**Comment by Videogamers0** [comment]
Button.Styles inside of a Button should work. Just be aware of the scope. A style won't affect anything that's not a child of the scope where it is defined.

This worked fine for me:

```xaml
<Button>
    <Button.Styles>
        <Style TargetType="TextBlock">
            <Setter Property="Foreground" Value="Red" />
        </Style>
    </Button.Styles>
    <StackPanel Orientation="Vertical">
        <TextBlock Text="Red background from style" />
        <TextBlock IsStyleable="False" Text="Default background, unstyled" />
        <TextBlock Text="Red background from style" />
    </StackPanel>
</Button>
```
