### ISSUE TITLE
FontFamily - Combobox and TextBox (inputfield)

### ISSUE THREAD

**Issue by rufreakde** [Videogamers0/MGUI#12]
How is it possible to change the FontFamily of these controls? (and maybe some others) To achieve a consistent look I would like to modify their font but FontFamily is an unknown property.

Thanks in advance!

**Comment by Videogamers0** [comment]
`MGTextBox` uses an `MGTextBlock` to render the text. You would want to do something like:

```c#
MGTextBox textBox = ...;
MGTextBlock textBlockComponent = textBox.TextBlockComponent.Element;
bool success = textBlockComponent.TrySetFont("familyname", fontSize);
```
Whichever family name you use must have already been registered to the `FontManager` via `AddFontSet(...)` instance method.

```c#
MGDesktop desktop = ...;
FontManager fm = desktop.FontManager;
fm.AddFontSet(new FontSet(...));
```

Note: If your `MGTextBox` is utilizing placeholder text (`MGTextBox.PlaceholderText` is not null), then you would probably also want to style the `MGTextBox.PlaceholderTextComponent` textblock.

For `MGComboBox<T>`, you would need to modify `MGComboBox.DropdownItemTemplate` and `MGComboBox.SelectedItemTemplate`. `DropdownItemTemplate` is invoked on each item in the combobox's `ItemsSource` to create the nested content. By default, it just creates an `MGButton`, and populates the button with a default `MGTextBlock` whose text is set to `item.ToString()`. You can override this behavior however you want. For example:

```c#
MGComboBox<double> comboBox = ...; // suppose we had a combobox whose ItemsSource is a collection of doubles
comboBox.DropdownItemTemplate = (item) =>
{
    string text = item.ToString("0.00"); // convert the decimal to a string with 2 decimal places
    MGButton button = comboBox.CreateDefaultDropdownButton(); // create the button that will host this combobox item

    //  Create the content of the button and customize its font family etc
    MGTextBlock textContent = new MGTextBlock(comboBox.ParentWindow, text);
    textContent.TrySetFont("fontFamily", 16);
    button.SetContent(textContent);

    return button;
};
```

There are also a couple settings named `DefaultFontFamily` that you could modify. One of them is an instance property in `ThemeFontSettings`:

```c#
MGDesktop desktop = ...;
MGTheme theme = desktop.Theme; //  Note: If the `MGWindow` specifies a theme, that theme would take priority. See also: MGElement.GetTheme()
theme.FontSettings.DefaultFontFamily = "fontFamilyName...";
```

The other one is an in instance property in `FontManager`.

```c#
MGDesktop desktop = ...;
FontManager fm = desktop.FontManager;
fm.DefaultFontFamily = "fontFamilyName...";
```

If a default is specified in both `FontManager` and `MGTheme`, the one in `MGTheme` takes precedence.

**Comment by rufreakde** [comment]
Hi thanks,
for the detailed explanation! I changed the default font! Since I only need one font in my game!
![image](https://github.com/Videogamers0/MGUI/assets/28104368/5169ae9a-a95b-4df0-877f-157f4c53174c)

Worked perfectly!
