### ISSUE TITLE
MVVM Community Toolkit integration/compatibility

### ISSUE THREAD

**Issue by orosbogdan** [Videogamers0/MGUI#16]
I wanted to know if this framework is compatible with MVVM Community toolkit, would be amazing to have these 2 integrated.

https://learn.microsoft.com/en-us/dotnet/communitytoolkit/mvvm/

**Comment by Videogamers0** [comment]
No idea. I've never used that framework before

**Comment by orosbogdan** [comment]
In WPF people usually use a MVVM framework(like this one or prism) to offer better testability and help manage with state management and communication between multiple views.

But I think MVVM support like behaviors, observable collections are outside the scope of this project, right ?
